In [13]:
import pandas as pd
import numpy as np

In [14]:
#df = pd.read_csv('data/datat.csv')
df = pd.read_excel('data.xlsx')

In [15]:
#Menampilkan informasi dari jumlah kolom dan baris, serta lima sampel teratas dari dataframe df_items
print('shape : {}'.format(df.shape))
df.head()

shape : (800, 7)

,Nama dan Tanggal,Nama,Tanggal,Rating,Review,Aspect Category,Polarity
0,Hendy Ucok Manurung\n22 April 2021\n\t,Hendy Ucok Manurung,22 April 2021,3,Sangat Membantu. Terutama di kondisi Pandemi. ...,Pelayanan,Negatif
1,Ratna Djauhari\n23 April 2021\n\t,Ratna Djauhari,23 April 2021,5,Baru pertama konsultasi dokter lewat halo doc ...,Pelayanan,Negatif
2,Karina Ismir\n22 April 2021\n\t,Karina Ismir,22 April 2021,1,astaga obatnya semakin lama beli obat di halo ...,Harga,Negatif
3,Sudi Ono\n23 April 2021\n\t,Sudi Ono,23 April 2021,5,Terimakasih Halodoc atas pelayanannya sangat b...,Pelayanan,Positif
4,Tetep Herman\n21 April 2021\n\t,Tetep Herman,21 April 2021,1,Ada yang nelpon ke no saya katanya dari halodo...,Sistem,Positif

In [16]:
#Mengeliminasi kolom tidak guna
raw = df.drop(columns=['Nama dan Tanggal', 'Nama', 'Tanggal','Aspect Category','Rating'])
raw.head(100)

                                               Review Polarity
0   Sangat Membantu. Terutama di kondisi Pandemi. ...  Negatif
1   Baru pertama konsultasi dokter lewat halo doc ...  Negatif
2   astaga obatnya semakin lama beli obat di halo ...  Negatif
3   Terimakasih Halodoc atas pelayanannya sangat b...  Positif
4   Ada yang nelpon ke no saya katanya dari halodo...  Positif
..                                                ...      ...
95  Aplikasi ini membuat dokter spt keluarga, saha...  Positif
96  Gimana sih ini. Masa dokter nya yg ngelewatin ...  Negatif
97  Kemaren tepatnya hari kamis tgl 04-maret-2021 ...  Negatif
98  Sangat membant untuk konsultasi dari rumah saj...  Positif
99  Parah vaksin lansia dosis ke 2 disini, parah b...  Positif

[100 rows x 2 columns]

In [17]:
print('Jumlah NaN value pada Review : ', len(raw[raw.Review.isna() == True]))

#Mengganti nilai NaN
#raw.Description.fillna('Tanpa Review', inplace = True)
#print('Jumlah NaN value pada Description : ', len(raw[raw.Description.isna() == True]))

Jumlah NaN value pada Review :  0

In [18]:
raw

                                                Review Polarity
0    Sangat Membantu. Terutama di kondisi Pandemi. ...  Negatif
1    Baru pertama konsultasi dokter lewat halo doc ...  Negatif
2    astaga obatnya semakin lama beli obat di halo ...  Negatif
3    Terimakasih Halodoc atas pelayanannya sangat b...  Positif
4    Ada yang nelpon ke no saya katanya dari halodo...  Positif
..                                                 ...      ...
795       Semudah diklik, praktis dan sangat membantuðŸ‘Œ  Positif
796        Pelayanannya ramah . Paham dengan bidangnya  Positif
797  bagus aplikasi nya terasa punya dokter pribadi...  Positif
798    sangat memudahkan konsultasi tanpa keluar rumah  Positif
799     Sangat membantu dan pelayanan dokter memuaskan  Positif

[800 rows x 2 columns]

In [21]:
raw = raw.rename(columns={'Review':'review','Polarity':'polarity'})
raw

                                                review polarity
0    Sangat Membantu. Terutama di kondisi Pandemi. ...  Negatif
1    Baru pertama konsultasi dokter lewat halo doc ...  Negatif
2    astaga obatnya semakin lama beli obat di halo ...  Negatif
3    Terimakasih Halodoc atas pelayanannya sangat b...  Positif
4    Ada yang nelpon ke no saya katanya dari halodo...  Positif
..                                                 ...      ...
795       Semudah diklik, praktis dan sangat membantuðŸ‘Œ  Positif
796        Pelayanannya ramah . Paham dengan bidangnya  Positif
797  bagus aplikasi nya terasa punya dokter pribadi...  Positif
798    sangat memudahkan konsultasi tanpa keluar rumah  Positif
799     Sangat membantu dan pelayanan dokter memuaskan  Positif

[800 rows x 2 columns]

In [22]:
raw.to_csv('data/data_raw.csv', index=False)

In [23]:
raw.head()

                                              review polarity
0  Sangat Membantu. Terutama di kondisi Pandemi. ...  Negatif
1  Baru pertama konsultasi dokter lewat halo doc ...  Negatif
2  astaga obatnya semakin lama beli obat di halo ...  Negatif
3  Terimakasih Halodoc atas pelayanannya sangat b...  Positif
4  Ada yang nelpon ke no saya katanya dari halodo...  Positif